# Generated by Django 2.2 on 2018-10-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0002_auto_20181029_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='No Description Available', max_length=300),
        ),
    ]
