# Generated by Django 2.1.2 on 2018-11-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0003_task_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.CharField(default='General Event', max_length=100),
        ),
    ]
