# Generated by Django 2.1.2 on 2018-11-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=150)),
                ('eventDescription', models.CharField(default='No Description Available', max_length=500)),
                ('eventAmount', models.CharField(default='0', max_length=10)),
                ('eventGoal', models.CharField(default='0', max_length=10)),
                ('eventCreated', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eventsdb',
            },
        ),
    ]
